namespace aoc2023_day02
{
    public class Game
    {
        public IList<Set> Sets { get; set; } = [];
        public int Id { get; set; }

        /// <summary>
        /// This was 90% successfully generated by Copilot
        /// </summary>
        /// <param name="s"></param>
        /// <returns></returns>
        public static Game Parse(string s)
        {
            var game = new Game();
            var elements = s.Split(':');
            game.Id = int.Parse(elements[0].Replace("Game", "").Trim());

            var sets = elements[1].Split(';');
            foreach (var set in sets)
            {
                var colors = set.Split(',');
                var red = 0;
                var green = 0;
                var blue = 0;
                foreach (var color in colors)
                {
                    if (color.Contains("red"))
                    {
                        red = int.Parse(color.Replace("red", "").Trim());
                    }
                    else if (color.Contains("green"))
                    {
                        green = int.Parse(color.Replace("green", "").Trim());
                    }
                    else if (color.Contains("blue"))
                    {
                        blue = int.Parse(color.Replace("blue", "").Trim());
                    }
                }

                game.Sets.Add(new Set { Red = red, Green = green, Blue = blue});
            }

            return game;
        }
    }
}
